# my global config
global:
  scrape_interval: 30s # Set the scrape interval to every 30 seconds. Default is every 1 minute.
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.

scrape_configs:
  - job_name: "webapi"
    static_configs:
      - targets: ["webapi:5000"]